language: scala
sudo: false

scala:
  - 2.12.6
  - 2.11.12

jdk:
  - oraclejdk8

# cache config taken from http://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
